# Generated by Django 5.2.5 on 2025-09-08 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('material_code', models.CharField(blank=True, max_length=20)),
                ('youngs_modulus', models.FloatField(help_text="Young's modulus in GPa")),
                ('tensile_strength', models.FloatField(help_text='Tensile strength in MPa')),
                ('shear_strength', models.FloatField(help_text='Shear strength in MPa')),
                ('density', models.FloatField(help_text='Density in g/cm³')),
                ('corrosion_resistance', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materialien',
                'db_table': 'tbl_materials',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('material_code',), name='unique_material_code')],
            },
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, choices=[('fits', 'fits'), ('fasteners', 'fasteners'), ('tolerances', 'tolerances'), ('bearings', 'bearings'), ('gears', 'gears'), ('springs', 'springs'), ('shafts', 'shafts'), ('couplings', 'couplings')], max_length=30, verbose_name='Anwendungsbereich')),
                ('standard_number', models.CharField(help_text='z.B. DIN EN ISO 9001:2015', max_length=50, unique=True, verbose_name='Normnummer')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('short_title', models.CharField(blank=True, max_length=100, verbose_name='Kurztitel')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Kategorie')),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('norm', 'Norm'), ('guideline', 'Richtlinie'), ('specification', 'Spezifikation'), ('regulation', 'Verordnung')], default='standard', max_length=20, verbose_name='Typ')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('draft', 'Entwurf'), ('deprecated', 'Veraltet'), ('withdrawn', 'Zurückgezogen')], default='active', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('scope', models.TextField(blank=True, verbose_name='Anwendungsbereich')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='Version')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Veröffentlichungsdatum')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('link', models.URLField(blank=True, help_text='Link zur offiziellen Dokumentation', verbose_name='Externer Link')),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='media/standards/datasheets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt'])], verbose_name='Datenblatt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('reference_documents', models.ManyToManyField(blank=True, to='main.standards', verbose_name='Referenzdokumente')),
            ],
            options={
                'verbose_name': 'Standard/Norm',
                'verbose_name_plural': 'Standards/Normen',
                'db_table': 'tbl_standards',
                'ordering': ['standard_number', 'publication_date'],
                'indexes': [models.Index(fields=['standard_number'], name='tbl_standar_standar_4f54c6_idx'), models.Index(fields=['category'], name='tbl_standar_categor_02b8af_idx'), models.Index(fields=['status'], name='tbl_standar_status_5ad656_idx'), models.Index(fields=['publication_date'], name='tbl_standar_publica_5f1172_idx')],
            },
        ),
    ]
